### Frontend
[datalog_logging]
# log typed version
typed = false
# steps to log
module = false
verbose_output = false


### IR
[ir_logging]
# log typed version
typed = false
# lowerings
module = false
lowerings = false
# Optimizations
analysis = false
control_graph = false
optimizations = false
# Stats
stats_before_lowering = false
stats_before_optimization = false
stats_after_optimization = false


### Viatra
[viatra_logging]
# log typed version
typed = false
# base module and lowerings
module = false
lowerings = false
# psystem code
psystem = false

[viatra_options]
apply_double_aggregation_rewrite = true